const ErrorCode = {
  E_NO_LIBRARY_PERMISSION: 'E_NO_LIBRARY_PERMISSION',
  E_NO_CAMERA_PERMISSION: 'E_NO_CAMERA_PERMISSION',
  E_PICKER_CANCELLED: 'E_PICKER_CANCELLED',
  UNAUTHORIZED: 'Unauthorized',
  ERR_NETWORK: 'ERR_NETWORK',
};

export default ErrorCode;
